# Generated by Django 4.2.27 on 2026-01-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_crimescene_remove_case_updated_at_case_complainants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(verbose_name='متن بازجویی')),
                ('score', models.PositiveSmallIntegerField(default=1, verbose_name='امتیاز (۱-۱۰)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interrogator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام متهم')),
                ('details', models.TextField(verbose_name='جزئیات')),
                ('is_main_suspect', models.BooleanField(default=False, verbose_name='متهم اصلی')),
                ('is_on_board', models.BooleanField(default=False, verbose_name='روی تخته')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='InterrogationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.PositiveSmallIntegerField(verbose_name='امتیاز نهایی')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('notes', models.TextField(blank=True, null=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('interrogation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='investigation.interrogation')),
            ],
        ),
        migrations.AddField(
            model_name='interrogation',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='investigation.suspect'),
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='علت اتصال')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_connections', to='cases.case')),
                ('from_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='evidence.evidence')),
                ('from_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='investigation.suspect')),
                ('to_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='evidence.evidence')),
                ('to_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='investigation.suspect')),
            ],
        ),
    ]
