# Generated by Django 4.2.27 on 2026-01-06 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_alter_case_status'),
        ('investigation', '0002_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان حکم')),
                ('result', models.CharField(choices=[('INNOCENT', 'بی\u200cگناه'), ('GUILTY', 'گناهکار')], max_length=10, verbose_name='رای نهایی')),
                ('punishment', models.TextField(blank=True, null=True, verbose_name='مجازات')),
                ('description', models.TextField(verbose_name='توضیحات قاضی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='cases.case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge_verdicts', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='investigation.suspect')),
            ],
        ),
    ]
