# Generated by Django 4.2.27 on 2026-01-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0003_alter_case_status'),
        ('investigation', '0003_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARREST', 'حکم بازداشت'), ('INTERROGATION', 'حکم بازجویی'), ('SEARCH', 'حکم تفتیش')], default='INTERROGATION', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('description', models.TextField(verbose_name='علت درخواست حکم')),
                ('approver_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات تاییدکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_warrants', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warrants', to='cases.case')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_warrants', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrants', to='investigation.suspect')),
            ],
        ),
    ]
