# Generated by Django 4.2.27 on 2026-01-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_warrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام متهم'),
        ),
    ]
