# Generated by Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0005_suspect_first_name_suspect_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شناسایی'),
        ),
        migrations.CreateModel(
            name='RewardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_full_name', models.CharField(blank=True, max_length=255, verbose_name='نام متهم')),
                ('suspect_national_code', models.CharField(blank=True, max_length=10, verbose_name='کد ملی متهم')),
                ('description', models.TextField(verbose_name='توضیحات گزارش')),
                ('status', models.CharField(choices=[('PO', 'در انتظار بررسی افسر'), ('PD', 'در انتظار بررسی کارآگاه'), ('AP', 'تایید نهایی'), ('RE', 'رد شده')], default='PO', max_length=2)),
                ('officer_notes', models.TextField(blank=True, verbose_name='یادداشت افسر')),
                ('detective_notes', models.TextField(blank=True, verbose_name='یادداشت کارآگاه')),
                ('reward_amount', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ پاداش')),
                ('tracking_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_detective_reviews', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_officer_reviews', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_payments', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_reports', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_reports', to='investigation.suspect')),
            ],
        ),
    ]
