# Generated by Django 4.2.27 on 2026-02-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_status"),
        ("investigation", "0006_rewardreport_and_suspect_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verdict",
            options={"verbose_name": "حکم قضایی", "verbose_name_plural": "احکام قضایی"},
        ),
        migrations.AlterUniqueTogether(
            name="verdict",
            unique_together={("case", "suspect")},
        ),
    ]
