# Generated by Django 4.2.27 on 2026-02-19 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0007_alter_verdict_options_alter_verdict_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interrogation',
            name='score',
        ),
        migrations.AddField(
            model_name='interrogation',
            name='interrogator_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='امتیاز بازجو (۱-۱۰)'),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_interrogations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='supervisor_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز مافوق (۱-۱۰)'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='interrogator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interrogations', to=settings.AUTH_USER_MODEL),
        ),
    ]
