# Generated by Django 4.2.27 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0008_remove_interrogation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suspects/', verbose_name='تصویر متهم'),
        ),
    ]
