# Generated by Django 4.2.27 on 2026-02-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0009_suspect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogationfeedback',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interrogationfeedback',
            name='chief_notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت رئیس پلیس'),
        ),
        migrations.AddField(
            model_name='interrogationfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interrogationfeedback',
            name='is_chief_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید شده توسط رئیس پلیس'),
        ),
        migrations.AlterField(
            model_name='interrogationfeedback',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captain_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogationfeedback',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط کاپیتان'),
        ),
        migrations.AlterField(
            model_name='interrogationfeedback',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت کاپیتان'),
        ),
    ]
