# Generated by Django 4.2.27 on 2026-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0010_interrogationfeedback_chief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interrogationfeedback',
            name='final_score',
        ),
        migrations.AlterField(
            model_name='interrogationfeedback',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='نظر نهایی کاپیتان'),
        ),
    ]
