# Generated by Django 4.2.27 on 2026-02-19 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0011_remove_interrogationfeedback_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrogation',
            name='interrogator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogations', to=settings.AUTH_USER_MODEL, verbose_name='کارآگاه'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='interrogator_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز کارآگاه (۱-۱۰)'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_interrogations', to=settings.AUTH_USER_MODEL, verbose_name='گروهبان'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='supervisor_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز گروهبان (۱-۱۰)'),
        ),
    ]
