# Generated by Django 4.2.27 on 2026-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0012_alter_interrogation_interrogator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="is_arrested",
            field=models.BooleanField(default=False, verbose_name="دستگیر شده"),
        ),
    ]
