# Generated by Django 4.2.27 on 2026-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0013_suspect_is_arrested"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDENTIFIED", "شناسایی شده"),
                    ("UNDER_ARREST", "در حال دستگیری (تایید شده)"),
                    ("ARRESTED", "دستگیر شده"),
                ],
                default="IDENTIFIED",
                max_length=20,
                verbose_name="وضعیت مظنون",
            ),
        ),
    ]
