# Generated by Django 4.2.27 on 2026-02-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0014_suspect_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suspect",
            name="status",
        ),
    ]
