# Generated by Django 4.2.27 on 2026-02-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0015_remove_suspect_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDENTIFIED", "شناسایی\u200cشده"),
                    ("UNDER_ARREST", "در حال دستگیری"),
                    ("ARRESTED", "دستگیر شده"),
                ],
                default="IDENTIFIED",
                max_length=20,
                verbose_name="وضعیت مظنون",
            ),
        ),
    ]
