# Generated by Django 4.2.27 on 2026-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0016_suspect_status_readd"),
    ]

    operations = [
        migrations.AddField(
            model_name="interrogation",
            name="is_interrogator_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="تایید نهایی کارآگاه"
            ),
        ),
        migrations.AddField(
            model_name="interrogation",
            name="is_supervisor_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="تایید نهایی گروهبان"
            ),
        ),
    ]
