# Generated by Django 4.2.27 on 2026-02-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0017_interrogation_is_interrogator_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interrogationfeedback",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[("INNOCENT", "بی\u200cگناه"), ("GUILTY", "گناهکار")],
                max_length=10,
                null=True,
                verbose_name="رای کاپیتان",
            ),
        ),
    ]
