# Generated by Django 4.2.27 on 2026-02-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0018_interrogationfeedback_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardreport",
            name="reward_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                unique=True,
                verbose_name="کد پاداش ۶ رقمی",
            ),
        ),
    ]
