# Generated by Django 4.2.27 on 2026-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0019_rewardreport_reward_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='bail_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ وثیقه (ریال)'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='bail_paid',
            field=models.BooleanField(default=False, verbose_name='وثیقه پرداخت شده'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='bail_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت وثیقه'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='bail_tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری وثیقه'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='fine_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ جریمه (ریال)'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='fine_paid',
            field=models.BooleanField(default=False, verbose_name='جریمه پرداخت شده'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='fine_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت جریمه'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='fine_tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پیگیری جریمه'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('IDENTIFIED', 'شناسایی\u200cشده'), ('UNDER_ARREST', 'در حال دستگیری'), ('ARRESTED', 'دستگیر شده'), ('FREE', 'آزاد شده (با قرار وثیقه)')], default='IDENTIFIED', max_length=20, verbose_name='وضعیت مظنون'),
        ),
    ]
