# Generated by Django 4.2.27 on 2026-01-01 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_crimescene_remove_case_updated_at_case_complainants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_evidences', to='cases.case')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('medical_follow_up', models.TextField(blank=True, null=True, verbose_name='نتیجه پیگیری پزشکی')),
                ('database_follow_up', models.TextField(blank=True, null=True, verbose_name='نتیجه پیگیری بانک داده')),
            ],
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('owner_full_name', models.CharField(max_length=255, verbose_name='نام کامل صاحب مدرک')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
            ],
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='OtherEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
            ],
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('model_name', models.CharField(max_length=100, verbose_name='مدل')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پلاک')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سریال')),
            ],
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='WitnessTestimony',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('transcript', models.TextField(verbose_name='رونوشت صحبت\u200cها')),
                ('media', models.FileField(blank=True, null=True, upload_to='evidence/witness/', verbose_name='فایل مرتبط')),
            ],
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/images/')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evidence.evidence')),
            ],
        ),
    ]
