# Generated by Django 4.2.27 on 2026-01-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_on_board',
            field=models.BooleanField(default=False, verbose_name='روی تخته'),
        ),
    ]
