# Generated by Django 4.2.27 on 2026-01-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_time', models.DateTimeField(verbose_name='زمان وقوع')),
                ('location', models.CharField(max_length=255, verbose_name='محل وقوع')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(blank=True, related_name='involved_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='crime_level',
            field=models.IntegerField(choices=[(3, 'سطح ۳ (جرائم خرد)'), (2, 'سطح ۲ (جرائم بزرگ)'), (1, 'سطح ۱ (جرائم کلان)'), (0, 'سطح بحرانی')], default=3, verbose_name='سطح جرم'),
        ),
        migrations.AddField(
            model_name='case',
            name='review_notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت داور'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PT', 'در انتظار بررسی کارآموز'), ('PO', 'در انتظار تایید افسر'), ('AC', 'در جریان'), ('RE', 'نیازمند اصلاح توسط شاکی'), ('CA', 'باطل شده'), ('SO', 'مختومه')], default='PT', max_length=2, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='case',
            name='submission_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(default=1, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='SceneWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.crimescene')),
            ],
        ),
        migrations.AddField(
            model_name='crimescene',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene_data', to='cases.case'),
        ),
        migrations.CreateModel(
            name='CaseComplainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant_details', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
