# Generated by Django 4.2.27 on 2026-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_crimescene_remove_case_updated_at_case_complainants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PT', 'در انتظار بررسی کارآموز'), ('PO', 'در انتظار تایید افسر'), ('AC', 'در جریان'), ('PS', 'در انتظار تایید گروهبان (حل پرونده)'), ('PC', 'در انتظار تایید نهایی رئیس پلیس'), ('RE', 'نیازمند اصلاح توسط شاکی'), ('CA', 'باطل شده'), ('SO', 'مختومه')], default='PT', max_length=2, verbose_name='وضعیت'),
        ),
    ]
