# Generated by Django 4.2.27 on 2026-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("PT", "در انتظار بررسی کارآموز"),
                    ("PO", "در انتظار تایید مقام مافوق"),
                    ("AC", "در جریان"),
                    ("PS", "در انتظار تایید گروهبان (حل پرونده)"),
                    ("PC", "در انتظار تایید نهایی رئیس پلیس"),
                    ("RE", "نیازمند اصلاح توسط ثبت\u200cکننده"),
                    ("CA", "باطل شده"),
                    ("SO", "مختومه"),
                ],
                default="PT",
                max_length=2,
                verbose_name="وضعیت",
            ),
        ),
    ]
