# Generated by Django 4.2.27 on 2026-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_case_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("PT", "در انتظار بررسی کارآموز"),
                    ("PO", "در انتظار تایید افسر"),
                    ("AC", "در جریان"),
                    ("IP", "در حال دستگیری متهم"),
                    ("PS", "در انتظار تایید گروهبان (حل پرونده)"),
                    ("PC", "در انتظار تایید نهایی رئیس پلیس"),
                    ("RE", "نیازمند اصلاح توسط شاکی"),
                    ("CA", "باطل شده"),
                    ("SO", "مختومه"),
                ],
                default="PT",
                max_length=2,
                verbose_name="وضعیت",
            ),
        ),
    ]
